version: '3'

services:
  app:
    container_name: front_end
    build: .
    ports: 
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - my-network
